### ISSUE TITLE
NVDA not supported

### ISSUE THREAD

**Issue by DeanNeal** [guidepup/setup#18]
I've faced an issue with tests launching.
```npx @guidepup/setup``` doesn't work for me

![image](https://user-images.githubusercontent.com/5802949/227944315-c115a93b-b6c5-4f1e-ab88-e3b2381d1be7.png)
It looks like something wrong with my local environment, but I can't find the reason.

**Comment by cmorten** [comment]
Hi @DeanNeal is this issue still happening for you? Going by https://github.com/guidepup/guidepup-playwright/issues/8 it sounds like it might be working locally for you, just not in a docker container?

**Comment by DeanNeal** [comment]
Hi @cmorten This issue is no longer reproducible. I have only issue with docker you mentioned https://github.com/guidepup/guidepup-playwright/issues/8
