### ISSUE TITLE
Provide manual setup instructions

### ISSUE THREAD

**Issue by diegohaz** [guidepup/setup#20]
Hello! Thank you for the amazing work on this project.

I think it would be good to add manual setup instructions. People may not feel comfortable running an npm script that requires admin credentials.

**Comment by cmorten** [comment]
Hey @diegohaz 👋 

Good shout 😄 daft thing is I’m sure I did have some and then got carried away seeing if could use UI automation locally and deleted it 😂 will have a dig and revive the manual instructions 😊

**Comment by cmorten** [comment]
Hey @diegohaz, please see https://www.guidepup.dev/docs/guides/manual-voiceover-setup

Feel free to reopen / raise another issue (or PR into https://github.com/guidepup/guidepup.dev) if not what was expecting or if have further suggestions!
